x-defaults:
  network: &network
    networks:
      - net

services:
  php:
    image: lamp
    ports:
      - 80:80
      - 443:443
    volumes:
      - workspace:/var/www
    configs:
      - source: apache-vhosts
        target: /etc/apache2/sites-available/000-default.conf
      - source: php-ini
        target: /usr/local/etc/php/conf.d/local.ini
    <<: *network

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pwd
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=
    volumes:
      - data:/var/lib/mysql
    secrets:
      - db_pwd
    configs:
      - source: mysqld_config
        target: /etc/mysql/conf.d/mysqld.cnf
    <<: *network


networks:
  net:

secrets:
  db_pwd:
    file: ./secrets/mysql/root_password.txt

configs:
  apache-vhosts:
    file: ./apache/vhosts.conf
  php-ini:
    file: ./php/local.ini
  mysqld_config:
    file: ./mysql/mysqld.cnf

volumes:

  workspace:

    external: true

  data:

    external: true
